[package]
name    = "db_utils"
version = "0.1.0"
edition = "2021"


[dependencies]
serde        = { version = "1.0", features = ["derive"] }
jsonwebtoken = { version = "9.3.0", optional = true }
strum        = { version = "0.26", features = ["derive"] }
